name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.sha }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Set KUBECONFIG from secret
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ${{ github.workspace }}/kubeconfig
          cat ${{ github.workspace }}/kubeconfig | head -n 5  # Optional: Preview top lines for debug

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          kubectl apply -f k8s_deployment_v1.yaml
          # Uncomment if you need these:
          # kubectl apply -f k8s/hpa.yaml
          # kubectl apply -f k8s/ingress.yaml
