name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout source code
      - name: Checkout code
        uses: actions/checkout@v2

      # ✅ Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ✅ Step 3: Log in to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ Step 4: Build & push Docker image
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # ✅ Step 5: Install kubectl CLI
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      # ✅ Step 6: Create kubeconfig from base64 secret
      - name: Create kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ${{ github.workspace }}/kubeconfig
        shell: bash

      # ✅ Step 7: Deploy to Kubernetes
      - name: Deploy to EKS
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          kubectl apply -f k8s_deployment_v1.yaml
          # Optional:
          # kubectl apply -f k8s/hpa.yaml
          # kubectl apply -f k8s/ingress.yaml
